version: "3"
services:
  backend:
    build: .
    environment:
      - HTTP_PORT=${API_PORT}
      - HTTP_ENDPOINT=${API_ENDPOINT}
      - JWKS_URI=${JWKS_URI}
      - AUTH_PROVIDER_DOMAIN=${AUTH_PROVIDER_DOMAIN}
      - AUTH_PROVIDER_CLIENT_ID=${AUTH_PROVIDER_CLIENT_ID}
      - AUTH_PROVIDER_CLIENT_SECRET=${AUTH_PROVIDER_CLIENT_SECRET}
    ports:
      - ${API_PORT}:${API_PORT}
  frontend:
    build: frontend/${AUTH_PROVIDER}
    ports:
      - ${WEB_PORT}:80